trigger: 
- master
pool: 
  vmImage: ubuntu-latest
variables: 
  name: Mohith
stages: 
- stage: variable_groups
  displayName:  displaying variable groups
  jobs: 
  - job: Variable_groups
    displayName: display variables
    variables: 
    - group: devops
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - script: 'my name is $(name)'