trigger: 
- master
pool: 
  vmImage: ubuntu-latest
stages: 
- stage: Build_stage
  displayName: Build nuget
  jobs: 
  - job: Build
    displayName: Build nuget packages
    variables: 
       BuildConfiguration: release
    steps: 
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          restoreArguments: '--configuration Release'
          feedsToUse: 'select'
        displayName: dotnet restore
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'
        displayName: dotnet build
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          versioningScheme: 'off'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'dc509265-52a3-4920-930e-bbe92d03ffc5'